### ISSUE TITLE
1.14 regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by faradaytrs** [UsefulWeb/AmoCRM#15]
```
/Users/imax/PhpstormProjects/globusmailer/server/node_modules/amocrm-js/dist/base/AmoConnection.js:81
      var _ref = _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee() {
                                                 ^

ReferenceError: regeneratorRuntime is not defined
    at /Users/imax/PhpstormProjects/globusmailer/server/node_modules/amocrm-js/dist/base/AmoConnection.js:81:50
    at /Users/imax/PhpstormProjects/globusmailer/server/node_modules/amocrm-js/dist/base/AmoConnection.js:113:6
    at Object.<anonymous> (/Users/imax/PhpstormProjects/globusmailer/server/node_modules/amocrm-js/dist/base/AmoConnection.js:175:2)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/imax/PhpstormProjects/globusmailer/server/node_modules/amocrm-js/dist/AmoCRM.js:9:22)
[nodemon] app crashed - waiting for file changes before starting...

```

**Comment by faradaytrs** [comment]
Я не использую babel. Все сразу работает в nodejs

**Comment by neizerth** [comment]
Исправлено в 1.0.15
