### ISSUE TITLE
При интеграции токена TypeError: Cannot read property 'then' of undefined 

### ISSUE THREAD

**Issue by amorev** [UsefulWeb/AmoCRM#31]
Для того, чтобы авторизация сохранялась между сессиями необходимо, при добавлении токена, обязательно сразу его обновлять. Иначе в connect() методе будет выполняться !this._Connected и, при отсутствии code, будет возвращаться не промис, а пустота.

```bash
TypeError: Cannot read property 'then' of undefined
    at AmoConnection.request (~/project\node_modules\amocrm-js\dist\base\AmoConnection.js:88:3
6)
    at request (~/project\node_modules\amocrm-js\dist\base\requests\ConnectionRequest.js:40:21
)
    at AmoCRM.handler [as request] (~/project\node_modules\amocrm-js\dist\base\requests\Connec
tionRequest.js:8:12)
    at initAmo (~/project\config\functions\bootstrap.js:102:32)
    at async module.exports (~/project\config\functions\bootstrap.js:112:3)
    at async Strapi.runBootstrapFunctions (~/project\node_modules\strapi\lib\Strapi.js:397:5)
    at async Strapi.load (~/project\node_modules\strapi\lib\Strapi.js:326:5)
    at async Strapi.start (~/project\node_modules\strapi\lib\Strapi.js:158:9)
````

## Костыльное решение

При добавлении токена сразу же его обновлять. То есть:

```javascript
crm.connection.setToken(currentToken, 0)
await crm.connection.refreshToken()
```

Но это неудобно:)

## Решение не уровне либы

Как решение на уровне либы - сделать метод setInitToken который будет принудительно обновлять токен при установке или же ставить _connected = true, чтобы не было таких ошибок

**Comment by amorev** [comment]
Ну тогда можно чуток доработать механизм так, чтобы время получения токена норм сохранялось.

И все же - когда токен протухнет и мы перезапустимся все упадет - по коду оно не зайдет в refreshToken

**Comment by neizerth** [comment]
@amorev Я могу хранить время истечения токена в самом токене. Но по факту получится, что я буду видоизменять то, что пришло по API, добавляя поле expires_at. Есть вероятность, что такое поле в API в итоге внедрят и будет происходить перезапись данных, что, на мой взгляд, не очень хорошо. 

В принципе, я могу сделать поле, название которого с большой вероятностью не появится. Но идея подмены оригинальных данных мне не очень нравится.

> И все же - когда токен протухнет и мы перезапустимся все упадет - по коду оно не зайдет в refreshToken

Да, поэтому нужно хранить в файле не только содержимое токена, но и по событию получения нового токена записывать дату получения токена.

**Comment by neizerth** [comment]
@amorev Внедрено начиная с v2.0.6
